# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78161f33dc0bf8d17c3952e2593939c61a2f6c81837819516d4b24c83a254183370e88a8ff96b525cfcf5075cde31c4a8f9df08914de3022d31566c7d310dd5

test:
  secret_key_base: 8dada6880f796162bdae6017184930076255568ee40abcea4743c23349d28f8c4ca283b2f1019d7a57bcb80cf3c369c68a81d8ee93dd007ae881ff842bf81917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
